# Generated by Django 5.1.6 on 2025-02-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.CharField(default="test", max_length=100),
        ),
    ]
