# Generated by Django 5.1.6 on 2025-02-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0002_post_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="tag",
            new_name="title_tag",
        ),
    ]
