# Generated by Django 5.1.6 on 2025-02-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0005_category_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(default="test", max_length=255),
        ),
    ]
