# Generated by Django 5.1.6 on 2025-03-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0006_alter_category_name_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myblog.category"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="yyy", max_length=100),
        ),
    ]
