# Generated by Django 5.1.6 on 2025-04-06 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0007_alter_post_category_alter_post_title_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(default="test", max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="test", max_length=100),
        ),
    ]
