# Generated by Django 5.1.6 on 2025-03-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0007_alter_post_category_alter_post_title_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(default="test", max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_tag",
            field=models.CharField(default="test", max_length=100),
        ),
    ]
