# Generated by Django 5.1.6 on 2025-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0008_category_slug_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category_slug",
            field=models.SlugField(default="test", max_length=255),
        ),
    ]
