# Generated by Django 5.1.6 on 2025-03-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0010_alter_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(default="test", max_length=255),
        ),
    ]
